name: Elm CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - serverless-latest
env:
  SESSION_SECRET: hello

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js 20
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: node_modules-node-v${{ matrix.node }}-1-${{ hashFiles('package-lock.json') }}
      - name: Cache ~/.elm
        uses: actions/cache@v4
        with:
          path: ~/.elm
          key: elm-${{ hashFiles('elm.json', 'elm-tooling.json', 'generator/elm.json', 'review/elm.json', 'examples/routing/elm.json', 'examples/escaping/elm.json', 'examples/base-path/elm.json') }}
      - name: Download lamdera
        run: curl https://static.lamdera.com/bin/linux/lamdera-next-alpine-musl -o /usr/local/bin/lamdera && chmod a+x /usr/local/bin/lamdera
      - name: npm ci
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        env:
          NO_ELM_TOOLING_INSTALL: 1
        run: npm ci
      - name: elm-tooling install
        run: npx --no-install elm-tooling install
      - name: Install elm-instrument (for coverage tests)
        run: npm install -g elm-coverage
      - name: Add elm-review, elm and elm-format to path
        run: realpath node_modules/.bin >> $GITHUB_PATH
      - uses: sparksp/elm-review-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Generator
        run: npm run build:generator
      - name: Tests
        run: npm test
      - name: Build elm docs
        run: rm -rf elm-stuff && lamdera make --docs docs.json
      - name: Build base path example site
        run: cd examples/base-path && npm install && npx elm-pages build --base elm-pages && cd ../..
      - name: GitHub Pages Example Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./examples/base-path/dist

  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js 20
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: node_modules-node-v${{ matrix.node }}-1-${{ hashFiles('package-lock.json') }}
      - name: Cache ~/.elm
        uses: actions/cache@v4
        with:
          path: ~/.elm
          key: elm-${{ hashFiles('elm.json', 'elm-tooling.json', 'generator/elm.json', 'review/elm.json', 'examples/routing/elm.json', 'examples/escaping/elm.json', 'examples/base-path/elm.json') }}
      - name: Download lamdera
        run: curl https://static.lamdera.com/bin/linux/lamdera-next-alpine-musl -o /usr/local/bin/lamdera && chmod a+x /usr/local/bin/lamdera
      - name: npm ci
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        env:
          NO_ELM_TOOLING_INSTALL: 1
        run: npm ci
      - name: elm-tooling install
        run: npx --no-install elm-tooling install
      - name: Build Generator
        run: npm run build:generator
      - name: Setup for cypress
        run: (cd examples/end-to-end && rm -f formatted-elm.txt && npm install && npx elm-tooling install && rm -rf elm-stuff && npx elm-pages gen && lamdera make app/Route/Index.elm)
      - name: DB migration E2E test
        run: cd examples/end-to-end && node ../../generator/src/cli.js run TestMigration
      - name: Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: examples/end-to-end
          start: node ../../generator/src/cli.js dev --debug
          wait-on: "http://localhost:1234"
          wait-on-timeout: 120
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: examples/end-to-end/cypress/screenshots
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: examples/end-to-end/cypress/videos

  publish:
    needs: [build, cypress]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js 20
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-node-v${{ matrix.node }}-1-${{ hashFiles('package-lock.json') }}
      - name: npm ci
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        env:
          NO_ELM_TOOLING_INSTALL: 1
        run: npm ci
      - name: elm-tooling install
        run: npx --no-install elm-tooling install
      - name: Elm Publish
        uses: dillonkearns/elm-publish-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-elm: ./node_modules/.bin/elm
      - id: npm-publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
